
# html lang
language: zh

# main menu navigation
menu:
  Home: /
  About: /about
  Archives: /archives/ || archives
  Categories: /categories/ || categories
  Tags: /tags/ || tags
  Resume: /resume

# stylesheets loaded in the <head>
stylesheets:

stylesheets_preload:
- https://cdn.bootcss.com/highlight.js/9.6.0/styles/github.min.css # for highlight
- https://fonts.googleapis.com/css?family=Abril+Fatface&display=swap # for font
- https://cdnjs.cloudflare.com/ajax/libs/tocbot/4.4.2/tocbot.css # for toc basic style

# scripts loaded in the end of the body
scripts_defer:
- https://cdn.bootcss.com/highlight.js/9.6.0/highlight.min.js # for highlight
- /js/paper.js # for basic script


social:
  Github: https://github.com/GoodNight-Git
  #Codepen: https://codepen.io/yours
  #Dribbble: https://dribbble.com/yours
  #Twitter: https://twitter.com/yours
  #知乎: https://www.zhihu.com/people/yours
  掘金: https://juejin.im/user/5cb1ed9b5188251b090acc5c
  Mail: mailto:goodnightlilanhui@gmail.com
  # and more, you can add other link by the same way

# Uncomment to disable sidebar
# toc: false
# link: false
# archives: false
# categories: false
# tags: false

# theme color
main_color: default # forest | grass | sky | sun | sea

# google Analytics
google_analytics_id: UA-171806323-1

# commend module
comment:
  enable: false
  appId: WJeMts5Pt6bfh1AmBPQ7Dvy3-gzGzoHsz
  appKey: 6mKl25zRgrHVHLnCaA2pIYAI
  placeholder: Good night. Take a rest.
  notify: false
  verify: false
  avatar: mp
